# Generated by Django 2.1.1 on 2018-12-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180916_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(default='DISPONÍVEL', max_length=20),
        ),
    ]
